# Generated by Django 6.0.2 on 2026-04-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitestat',
            options={'verbose_name': 'Site Statistic', 'verbose_name_plural': 'Site Statistics'},
        ),
        migrations.AlterField(
            model_name='sitestat',
            name='total_views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
